### ISSUE TITLE
IE throws stack overflow when importing Prompt.html resources

### ISSUE THREAD

**Issue by CharlesPockert** [aurelia/dialog#28]
![image](https://cloud.githubusercontent.com/assets/9073518/9850306/ab0351ca-5ae9-11e5-918f-b47440639d2e.png)

Of course I can't really get a stack trace, not had a good look yet, thought I'd log it, I'll PR it if I can figure it out and it helps you lot out :)

Works fine when I remove the dialog dependency (but then my dialogs don't work!)

FYI this works fine on FF/Chrome (as usual!)

**Comment by EisenbergEffect** [comment]
Two things:

1. @PWKad We need to remove the Prompt class. I designed that only as a simple example of library use and would rather it not be shipped with the library in a way that it can be used in other projects.
2. The actual bug probably relates to a templating bug that we are tracking in that library. When we resolve it (hopefully this week) then that should fix this issue.

**Comment by CharlesPockert** [comment]
Thanks @EisenbergEffect will wait patiently - my app is pretty much prod ready so I'll let you know how it goes down (it's replacing a SL app which was written using Caliburn.Micro which went down well :))

**Comment by hlj** [comment]
This problem still exists in 0.3.0 when importing dialog-footer.html.

**Comment by PWKad** [comment]
@hlj That's correct this bug https://github.com/aurelia/templating/issues/169 is tracking the issue.
